### ISSUE TITLE
RTFM wanted

### ISSUE THREAD

**Issue by tieugene** [minfrin/mod_dav_calendar#1]
Reading sources is usual but not for packaged product.
Something like HOWTO.md will be better

**Comment by minfrin** [comment]
Definitely - let me put something together to get this sorted.

**Comment by minfrin** [comment]
We have an FM!

**Comment by tieugene** [comment]
> We have an FM!

Great, thank you!

**Comment by minfrin** [comment]
...and we have our first release!
